"""added other details

Revision ID: f8744c27ea51
Revises: bba94e19041c
Create Date: 2025-07-24 22:28:27.677041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8744c27ea51'
down_revision: Union[str, Sequence[str], None] = 'bba94e19041c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_superadmin')
    # ### end Alembic commands ###
